### ISSUE TITLE
Private Key On Public Repo

### ISSUE THREAD

**Issue by pkurto16** [Swipe-Swap/SwipeSwapFrontend#3]
https://github.com/Swipe-Swap/SwipeSwapFrontend/blob/53eafc03f4818fb13e37f5e12348e9ea7bf30e74/swipeswap/server/src/main/resources/service-account.json

Can we try using a .env var here so the key isn't exposed to the public lol?

**Comment by HolographicX** [comment]
changed keys

**Comment by pkurto16** [comment]
I got another email, are these completed?

1. Log in to the Google Cloud Console and review the activity on your account. 
2. Revoke all (or listed) credentials for compromised Service Accounts. As every resource accessible to the Service Account may have been affected, it is best to rotate all credentials on potentially affected projects. For more details, review the instructions on [handling compromised GCP credentials](https://notifications.googleapis.com/email/redirect?t=AFG8qyXfXYiXN6rR39cSFqi2oBykoIhENVYPcUp5vNauyEzjCYb0VeMI3C8VNzPG5G5BMBsEVzKMD73CCvc98KB4I8XD9Gj27KXOo0I8qsjMju7XB4e0N3BSitOozmJ4WlMI6ePc7cQioAkjuJDbgPKpIsgHhdtsOZQLNNkZWphpd4NU3BfsCagwDQ5i_1x1Sd-VRWDDudiu5u-TqNYzfXnm4RnHz49vG46maxXEfIQROQ&r=eJwNx0EOwCAIBMAXVe79TQMbJcFiAA_9vZ3bjKqVNxGbb2ndvRsa-6QE79D66M8Kn5qQiwOCt_SxPHZ0Fi4&s=ALHZ2r4JMNCUHcx5NJMTrVu7eKIb). 
3. Delete all unauthorized VMs or resources if you see any. 
4. Take immediate steps to ensure that your Service Account credentials are not embedded in public source code systems, stored in download directories, or unintentionally shared in other ways.

**Comment by xanmankey** [comment]
That's my bad; we did 1 and 4 and created new credentials, but I didn't realize we had to revoke the old ones; I was under the impression that they automatically got revoked. I just revoked the old service-account key
